# Generated by Django 4.2.7 on 2023-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='integrated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
