# Generated by Django 4.2.7 on 2023-11-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_writeoff_writeoffitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writeoffitem',
            old_name='cart',
            new_name='write_off',
        ),
        migrations.AlterField(
            model_name='writeoffitem',
            name='item_location',
            field=models.ForeignKey(help_text='Обираємо компонент для списання з конкретного місця', on_delete=django.db.models.deletion.CASCADE, related_name='write_off_items', to='warehouse.itemlocation'),
        ),
        migrations.AlterField(
            model_name='writeoffitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Обираємо кількість компонентів для списання з конкретного місця'),
        ),
    ]
