# Generated by Django 4.2.7 on 2023-11-23 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0004_rename_cart_writeoffitem_write_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoff',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='order_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='reason',
            field=models.CharField(help_text='Коротко описуємо причину списання з балансу', max_length=255),
        ),
    ]
