# Generated by Django 5.0 on 2023-12-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_item_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='photo',
            new_name='image',
        ),
    ]
