# Generated by Django 5.0 on 2024-01-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_item_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
