# Generated by Django 5.0 on 2024-01-06 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_delete_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.attributename'),
        ),
    ]
