# Generated by Django 5.0 on 2024-01-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_attributename_alter_attribute_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together=set(),
        ),
    ]
