# Generated by Django 5.0 on 2024-01-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_alter_itemlocation_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlocation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.owner'),
        ),
    ]
