# Generated by Django 5.0 on 2024-01-09 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_alter_itemlocation_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemlocation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.item'),
        ),
        migrations.AlterField(
            model_name='itemlocation',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.owner'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together={('cart', 'name')},
        ),
        migrations.DeleteModel(
            name='AttributeName',
        ),
    ]
